name: Credit Score Modeling Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run EDA notebook
        run: |
          pip install nbconvert
          jupyter nbconvert --to notebook --execute notebooks/EDA.ipynb

      - name: Run Feature Engineering and Model Building notebook
        run: |
          pip install nbconvert
          jupyter nbconvert --to notebook --execute notebooks/feature_engineering_and_model_building.ipynb
